package com.example.clicktorun.utils

const val ACTION_START_RUN_SERVICE = "ACTION_START_RUN_SERVICE"
const val ACTION_PAUSE_RUN_SERVICE = "ACTION_PAUSE_RUN_SERVICE"
const val ACTION_CANCEL_RUN_SERVICE = "ACTION_CANCEL_RUN_SERVICE"
const val ACTION_NAVIGATE_TO_TRACKING = "ACTION_NAVIGATE_TO_TRACKING"
const val NOTIFICATION_CHANNEL_ID = "clicktorun_channel"
const val NOTIFICATION_CHANNEL_NAME = "ClickToRun"
const val NOTIFICATION_ID = 100