package com.example.clicktorun.utils

const val ACTION_NAVIGATE_TO_LOGIN = "ACTION_NAVIGATE_TO_LOGIN"
const val ACTION_START_RUN_SERVICE = "ACTION_START_RUN_SERVICE"
const val ACTION_PAUSE_RUN_SERVICE = "ACTION_PAUSE_RUN_SERVICE"
const val ACTION_CANCEL_RUN_SERVICE = "ACTION_CANCEL_RUN_SERVICE"
const val ACTION_NAVIGATE_TO_TRACKING = "ACTION_NAVIGATE_TO_TRACKING"
const val NOTIFICATION_CHANNEL_ID = "clicktorun_channel"
const val NOTIFICATION_CHANNEL_NAME = "ClickToRun"
const val NOTIFICATION_ID = 100
const val CLICK_TOLERANCE = 10f
const val REQUEST_CODE_TO_PICK_IMAGE = 183
const val ONE_MEGABYTE: Long = 1024 * 1024